db:
  username: postgres
  password: pass
  driver: PostgresDriver
  pool:
    size: 12
    timeout: 10
  url: postgres:5432
  hosts:
    - localhost
    - 127.0.0.1
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
  properties:
    first: 123
    second: 456
    third.value: Thir
repo:
  name: test
logging:
  level:
    org:
      springframework:
        jdbc:
          core: trace
    root: INFO
  file:
    name: test.log
    path: /
spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
  liquibase:
    change-log: classpath:liquibase/master/changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/scbt
    username: scbt
    password: scbt
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
        jdbc:
          batch_size: 50
    open-in-view: false
