db:
  username: postgres
  password: pass
  driver: PostgresDriver
  pool:
    size: 12
    timeout: 10
  url: postgres:5432
  hosts:
    - localhost
    - 127.0.0.1
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
  properties:
    first: 123
    second: 456
    third.value: Thir
repo:
  name: test
